name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 21.x

    - name: Setup OS dependencies
      run: |-
        sudo apt-get update
        sudo apt-get install -yy \
          libnss3 \
          libatk-bridge2.0-0 \
          libgtk-3-dev \
          libasound2 \
          xvfb

    - name: Install dependencies
      run: npm ci

    - name: Check for lint errors
      run: npm run lint

    - name: Run tests
      run: xvfb-run -a npm test
